### ISSUE TITLE
Add to the NPM registry

### ISSUE THREAD

**Issue by benjaminapetersen** [prestopasto/SCSS-Material-Shadows#1]
Since many are migrating away from `bower` in favor of just `npm` or `yarn`, consider adding this to the NPM registry.  Thx!

**Comment by prestopasto** [comment]
Good idea.  I myself haven't used bower on a project in a while.  I'll work on getting this moved over and update the readme.

**Comment by prestopasto** [comment]
Added to NPM.  See README for package name.
